/*
 * This source file was generated by the Gradle 'init' task
 */
package solace.vm.internal.harv

import kotlin.test.Test
import kotlin.test.assertEquals

class VirtualMachineTest {

    fun p(builderFun: (ProgramBuilder) -> List<Int>): VirtualMachine {
        val program = builderFun(ProgramBuilder())
        val programMemory = ListProgramMemory(program)
        val vm = VirtualMachine(programMemory)

        vm.run()

        return vm
    }

    @Test
    fun pushWorksLikePush() {
        val vm = p { builder ->
            builder
                .push(69)
                .push(2)
                .build()
        }

        assertEquals(2, vm.getStack().last())
    }

    @Test
    fun popWorksLikePop() {
        val vm = p { builder ->
            builder
                .push(69)
                .push(2)
                .pop()
                .build()
        }

        assertEquals(69, vm.getStack().last())
    }

    @Test
    fun addAdds() {
        val vm = p { builder ->
            builder
                .push(1)
                .push(2)
                .add()
                .build()
        }

        assertEquals(1 + 2, vm.getStack().last())
    }

    @Test
    fun subtractSubtracts() {
        val vm = p { builder ->
            builder
                .push(5)
                .push(2)
                .subtract()
                .build()
        }

        assertEquals(5 - 2, vm.getStack().last())
    }

    @Test
    fun multiplyMultiples() {
        val vm = p { builder ->
            builder
                .push(2)
                .push(3)
                .multiply()
                .build()
        }

        assertEquals(2 * 3, vm.getStack().last())
    }

    @Test
    fun divideDivides() {
        val vm = p { builder ->
            builder
                .push(6)
                .push(3)
                .divide()
                .build()
        }

        assertEquals(6 / 3, vm.getStack().last())
    }

    @Test
    fun modMods() {
        val vm = p { builder ->
            builder
                .push(7)
                .push(6)
                .mod()
                .build()
        }

        assertEquals(7 % 6, vm.getStack().last())
    }

    @Test
    fun negativeNegatives() {
        val vm = p { builder ->
            builder
                .push(1)
                .negative()
                .build()
        }

        assertEquals(-1, vm.getStack().last())
    }

    @Test
    fun duplicateDuplicates() {
        val vm = p { builder ->
            builder
                .push(69)
                .duplicate()
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(69, stack[0])
        assertEquals(69, stack[1])
    }

    @Test
    fun swapSwaps() {
        val vm = p { builder ->
            builder
                .push(1)
                .push(2)
                .swap()
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(2, stack[0])
        assertEquals(1, stack[1])
    }

    @Test
    fun jumpJumps() {
        val vm = p { builder ->
            builder
                /* 0x00 */.push(1)
                /* 0x02 */.jump(0x06u)
                /* 0x04 */.push(2)
                /* 0x06 */.push(3)
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(1, stack[0])
        assertEquals(3, stack[1])
    }

    @Test
    fun jumpIfTrueJumpsIfTrue() {
        val vm = p { builder ->
            builder
                /* 0x00 */.push(69)
                /* 0x02 */.push(1)
                /* 0x04 */.jumpIfTrue(0x08u)
                /* 0x06 */.push(24)
                /* 0x08 */.push(0)
                /* 0x0A */.jumpIfTrue(0x02u)
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(69, stack[0])
    }

    @Test
    fun equalEquals() {
        val vm = p { builder ->
            builder
                .push(69)
                .push(69)
                .equal()
                .push(69)
                .push(79)
                .equal()
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(1, stack[0])
        assertEquals(0, stack[1])
    }

    @Test
    fun notEqualNotEquals() {
        val vm = p { builder ->
            builder
                .push(69)
                .push(79)
                .notEqual()
                .push(69)
                .push(69)
                .notEqual()
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(1, stack[0])
        assertEquals(0, stack[1])
    }

    @Test
    fun lessThanLessThan() {
        val vm = p { builder ->
            builder
                .push(69)
                .push(79)
                .lessThan()
                .push(69)
                .push(69)
                .lessThan()
                .push(79)
                .push(69)
                .lessThan()
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(1, stack[0])
        assertEquals(0, stack[1])
        assertEquals(0, stack[2])
    }

    @Test
    fun greaterThanGreaterThan() {
        val vm = p { builder ->
            builder
                .push(79)
                .push(69)
                .greaterThan()
                .push(69)
                .push(69)
                .greaterThan()
                .push(69)
                .push(79)
                .greaterThan()
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(1, stack[0])
        assertEquals(0, stack[1])
        assertEquals(0, stack[2])
    }

    @Test
    fun lessOrEqualIsLessOrEqual() {
        val vm = p { builder ->
            builder
                .push(69)
                .push(79)
                .lessOrEqual()
                .push(69)
                .push(69)
                .lessOrEqual()
                .push(79)
                .push(69)
                .lessOrEqual()
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(1, stack[0])
        assertEquals(1, stack[1])
        assertEquals(0, stack[2])
    }

    @Test
    fun greaterOrEqualIsGreaterOrEqual() {
        val vm = p { builder ->
            builder
                .push(79)
                .push(69)
                .greaterOrEqual()
                .push(69)
                .push(69)
                .greaterOrEqual()
                .push(69)
                .push(79)
                .greaterOrEqual()
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(1, stack[0])
        assertEquals(1, stack[1])
        assertEquals(0, stack[2])
    }

    @Test
    fun logicalAndIsLogicalAnd() {
        val vm = p { builder ->
            builder
                .push(1)
                .push(1)
                .logicalAnd()
                .push(0)
                .push(1)
                .logicalAnd()
                .push(1)
                .push(0)
                .logicalAnd()
                .push(0)
                .push(0)
                .logicalAnd()

                .push(69)
                .push(69)
                .logicalAnd()
                .push(0)
                .push(69)
                .logicalAnd()
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(1, stack[0])
        assertEquals(0, stack[1])
        assertEquals(0, stack[2])
        assertEquals(0, stack[3])

        assertEquals(1, stack[4])
        assertEquals(0, stack[5])
    }

    @Test
    fun logicalOrIsLogicalOr() {
        val vm = p { builder ->
            builder
                .push(1)
                .push(1)
                .logicalOr()
                .push(0)
                .push(1)
                .logicalOr()
                .push(1)
                .push(0)
                .logicalOr()
                .push(0)
                .push(0)
                .logicalOr()

                .push(69)
                .push(69)
                .logicalOr()
                .push(0)
                .push(69)
                .logicalOr()
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(1, stack[0])
        assertEquals(1, stack[1])
        assertEquals(1, stack[2])
        assertEquals(0, stack[3])

        assertEquals(1, stack[4])
        assertEquals(1, stack[5])
    }

    @Test
    fun logicalNotIsLogicalNot() {
        val vm = p { builder ->
            builder
                .push(1)
                .logicalNot()
                .push(0)
                .logicalNot()
                .push(69)
                .logicalNot()
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(0, stack[0])
        assertEquals(1, stack[1])
        assertEquals(0, stack[2])
    }

    @Test
    fun nopIsDoingNothing() {
        val vm = p { builder ->
            builder
                .push(1)
                .nop()
                .nop()
                .nop()
                .nop()
                .nop()
                .nop()
                .push(2)
                .build()
        }

        val stack = vm.getStack().toList()

        assertEquals(1, stack[0])
        assertEquals(2, stack[1])
    }
}
