/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import solace.vm.internal.sim.netlist.*

class App {
    val greeting: String
        get() {
            return "Hello Worlda!"
        }
}

fun main() {
    val a = App(); System.err.print(a.greeting);
}
